#!/bin/bash
#
# Set up the Pi as a local-only WiFi access point (NetworkManager + dnsmasq),
# reachable at the same time as the existing wired (eth0) connection.
#
# - Does NOT share/route internet access from eth0 to WiFi clients (no NAT,
#   no IP forwarding) — it's purely so the robot arm app/server are reachable
#   over WiFi as well as ethernet. All the app's servers (port 80, 8080, 8082)
#   already bind 0.0.0.0, so no application changes are needed for this.
# - Safe to re-run: recreates the NetworkManager connection and dnsmasq
#   config idempotently.
#
# Usage (on the Raspberry Pi):
#   chmod +x install-wifi-ap.sh
#   sudo ./install-wifi-ap.sh [ssid] [password] [static-ip/prefix]
#
# Examples:
#   sudo ./install-wifi-ap.sh
#     -> SSID "RobotArm-$(hostname)", password prompted for, 192.168.4.1/24
#   sudo ./install-wifi-ap.sh RobotArm-Lab2 MyWifiPass123
#   sudo ./install-wifi-ap.sh RobotArm-Lab2 MyWifiPass123 192.168.5.1/24

set -e

CON_NAME="RobotArm-AP"
DNSMASQ_CONF="/etc/dnsmasq.d/robotarm-ap.conf"

if [ "$EUID" -ne 0 ]; then
    echo "Error: run this script with sudo"
    echo "  sudo ./install-wifi-ap.sh"
    exit 1
fi

SSID="${1:-RobotArm-$(hostname)}"
WIFI_PASSWORD="$2"
STATIC_IP="${3:-192.168.4.1/24}"

if [ -z "$WIFI_PASSWORD" ]; then
    read -r -s -p "WiFi password for '$SSID' (min 8 characters): " WIFI_PASSWORD
    echo ""
fi

if [ "${#WIFI_PASSWORD}" -lt 8 ]; then
    echo "Error: WiFi password must be at least 8 characters (WPA2 requirement)."
    exit 1
fi

if ! command -v nmcli >/dev/null; then
    echo "Error: NetworkManager (nmcli) not found. This script targets Raspberry Pi OS"
    echo "Bookworm+ (NetworkManager-based). Older dhcpcd-based images are not supported."
    exit 1
fi

AP_IP="${STATIC_IP%%/*}"

echo "=========================================="
echo "Robot Arm — WiFi access point setup"
echo "=========================================="
echo ""
echo "SSID:        $SSID"
echo "Static IP:   $STATIC_IP"
echo "Connection:  $CON_NAME (wlan0)"
echo ""

echo "Step 1: Enable WiFi radio"
nmcli radio wifi on
sleep 2
echo "  Done."
echo ""

echo "Step 2: Install dnsmasq (DHCP for AP clients — DNS disabled to avoid"
echo "         conflicting with any existing resolver on the Pi)"
if ! dpkg -s dnsmasq >/dev/null 2>&1; then
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y dnsmasq
fi
# Installing the package can auto-start it bound to all interfaces before
# it's scoped below — stop it first so it never listens broadly.
systemctl stop dnsmasq 2>/dev/null || true
echo "  Done."
echo ""

echo "Step 3: Scope dnsmasq to wlan0, DHCP only (no DNS)"
cat > "$DNSMASQ_CONF" <<EOF
# Robot Arm access point — DHCP only, scoped to wlan0. Generated by
# install-wifi-ap.sh — safe to regenerate by re-running that script.
interface=wlan0
bind-interfaces
except-interface=lo
port=0
dhcp-range=${AP_IP%.*}.10,${AP_IP%.*}.100,255.255.255.0,24h
dhcp-option=option:router,${AP_IP}
EOF
echo "  Wrote $DNSMASQ_CONF"
echo ""

echo "Step 4: Create/refresh the NetworkManager AP connection"
nmcli connection delete "$CON_NAME" >/dev/null 2>&1 || true
nmcli connection add type wifi ifname wlan0 con-name "$CON_NAME" autoconnect yes ssid "$SSID"
# ipv4.method manual (NOT "shared") — "shared" would enable NAT/IP-forwarding
# and route WiFi clients out through eth0 to the internet, which this script
# deliberately does not do.
nmcli connection modify "$CON_NAME" \
    802-11-wireless.mode ap \
    802-11-wireless.band bg \
    ipv4.method manual \
    ipv4.addresses "$STATIC_IP" \
    ipv6.method disabled \
    wifi-sec.key-mgmt wpa-psk \
    wifi-sec.psk "$WIFI_PASSWORD" \
    connection.autoconnect-priority 0
echo "  Done."
echo ""

echo "Step 5: Enable dnsmasq and bring up the access point"
systemctl enable --now dnsmasq
nmcli connection up "$CON_NAME"
echo "  Done."
echo ""

echo "=========================================="
echo "Setup complete"
echo "=========================================="
echo ""
echo "Connect to WiFi \"$SSID\", then browse to:"
echo "  http://$AP_IP"
echo ""
echo "The existing wired connection (eth0) is untouched and still works."
echo ""
echo "Verify:"
echo "  nmcli -t -f DEVICE,TYPE,STATE,CONNECTION device status"
echo "  ip addr show wlan0"
echo "  cat /proc/sys/net/ipv4/ip_forward   # should print 0 (no internet sharing)"
echo ""
echo "Uninstall:"
echo "  sudo nmcli connection delete $CON_NAME"
echo "  sudo rm $DNSMASQ_CONF"
echo "  sudo systemctl disable --now dnsmasq"
echo ""
