//************************************************************************************
//**  
//**  Source name:   D:\Dev\Robot Arm 3\Firmware\End Tool API ESP32\RobotArmv3_End_Tool_API.fcfx
//**  Title:         New Embedded Project
//**  Description:   
//**  Device:        ESP.ESP32.ESP32_WROOM_32
//**  
//**  Generated by:  Flowcode v11.0.2.15
//**  Date:          Monday, June 01, 2026 15:51:26
//**  Users:         1
//**  Registered to: BenR (82702381)
//**  Licence key: 95CJQR
//**  
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_ESP

#define MX_CAL_ESP

#define MX_CLK_SPEED 240000000

#define FCP_NULL Unconnected_Port


#define MX_CAL_ESP32
#define MX_ESP32_TYPE ESP32
#include <stdio.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_event_loop.h"
#include "nvs_flash.h"
#include "lwip/err.h"
#include "lwip/sys.h"
#include "sdkconfig.h"

/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"




/*========================================================================*\
   Use :Interrupt
\*========================================================================*/
  //Global code for [RXINT1]

  #define MX_UART1_INT

MX_UINT8 FCLV_LOOP1;
MX_UINT8 FCLV_LOOP2;
MX_UINT8 FCLV_LOOP3;
MX_UINT8 FCLV_LOOP4;
MX_UINT8 FCLV_LOOP5;
MX_UINT8 FCLV_LOOP6;
MX_UINT8 FCLV_LOOP7;
MX_UINT32 FCLV_LOOP8;
MX_UINT32 FCLV_LOOP9;
MX_UINT32 FCLV_LOOP10;
MX_UINT32 FCLV_LOOP11;

void FCM_RefreshRegisterArrayFromVariables();
void FCM_ApplyPendingHobbyServo();
void FCM_SendStatusPacketWithMultiReadData();
void FCM_UpdateAdcTelemetry();
void FCM_ProcessCommsByte();
void FCM_UpdateCurrentMeasurements();
void FCM_ServoBus_RX();
void FCM_SendStatusPacketNoData();
void FCM_SendStatusPacketWithData();
void FCM_WritePacketBytesToRegisters();
void FCM_ApplyWritableRegistersToVariablesAndHardware();
void FCM_ReadRegisterIntoReadValue();
MX_UINT8 FCD_01211_CircularBuffer1__LookForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT8 FCL_RESETFIND);
void FCD_01211_CircularBuffer1__GetArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FCD_01211_CircularBuffer1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT16 FCL_MAXLENGTH);
void FCD_01211_CircularBuffer1__PutArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
MX_UINT8 FCD_01211_CircularBuffer1__GetIndexedByte(MX_UINT16 FCL_ADDRESS);
MX_UINT8 FCD_01211_CircularBuffer1__WaitForValue(MX_CHAR *FCL_VALUE, MX_UINT16 FCLsz_VALUE, MX_UINT8 FCL_NUMCHARS, MX_UINT8 FCL_REMOVECONTENT, MX_UINT16 FCL_TIMEOUT);
MX_UINT16 FCD_01211_CircularBuffer1__GetNumberBytes();
MX_UINT16 FCD_01211_CircularBuffer1__PeekByte();
void FCD_01211_CircularBuffer1__PutString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
MX_UINT8 FCD_01211_CircularBuffer1__PutByte(MX_UINT8 FCL_DATA);
MX_UINT16 FCD_01211_CircularBuffer1__GetByte();
MX_UINT16 FCD_01211_CircularBuffer1__GetSize(MX_BOOL FCL_MODE);
void FCD_01211_CircularBuffer1__FlushBuffer();

/*========================================================================*\
   Use :SwitchSlide8
       :Macro function declarations
\*========================================================================*/
#define FCV_01508_SwitchSlide8__POLARITY (0)

MX_UINT8 FCD_01508_SwitchSlide8__ReadState();
void FCD_01508_SwitchSlide8__WaitUntilHigh();
void FCD_01508_SwitchSlide8__SetState(MX_BOOL FCL_STATE);
void FCD_01508_SwitchSlide8__WaitUntilLow();

/*========================================================================*\
   Use :SwitchSlide7
       :Macro function declarations
\*========================================================================*/
#define FCV_01507_SwitchSlide7__POLARITY (0)

MX_UINT8 FCD_01507_SwitchSlide7__ReadState();
void FCD_01507_SwitchSlide7__WaitUntilHigh();
void FCD_01507_SwitchSlide7__SetState(MX_BOOL FCL_STATE);
void FCD_01507_SwitchSlide7__WaitUntilLow();

/*========================================================================*\
   Use :SwitchSlide6
       :Macro function declarations
\*========================================================================*/
#define FCV_01506_SwitchSlide6__POLARITY (0)

MX_UINT8 FCD_01506_SwitchSlide6__ReadState();
void FCD_01506_SwitchSlide6__WaitUntilHigh();
void FCD_01506_SwitchSlide6__SetState(MX_BOOL FCL_STATE);
void FCD_01506_SwitchSlide6__WaitUntilLow();

/*========================================================================*\
   Use :SwitchSlide5
       :Macro function declarations
\*========================================================================*/
#define FCV_01505_SwitchSlide5__POLARITY (0)

MX_UINT8 FCD_01505_SwitchSlide5__ReadState();
void FCD_01505_SwitchSlide5__WaitUntilHigh();
void FCD_01505_SwitchSlide5__SetState(MX_BOOL FCL_STATE);
void FCD_01505_SwitchSlide5__WaitUntilLow();

/*========================================================================*\
   Use :SwitchSlide4
       :Macro function declarations
\*========================================================================*/
#define FCV_01504_SwitchSlide4__POLARITY (0)

MX_UINT8 FCD_01504_SwitchSlide4__ReadState();
void FCD_01504_SwitchSlide4__WaitUntilHigh();
void FCD_01504_SwitchSlide4__SetState(MX_BOOL FCL_STATE);
void FCD_01504_SwitchSlide4__WaitUntilLow();

/*========================================================================*\
   Use :SwitchSlide3
       :Macro function declarations
\*========================================================================*/
#define FCV_01503_SwitchSlide3__POLARITY (0)

MX_UINT8 FCD_01503_SwitchSlide3__ReadState();
void FCD_01503_SwitchSlide3__WaitUntilHigh();
void FCD_01503_SwitchSlide3__SetState(MX_BOOL FCL_STATE);
void FCD_01503_SwitchSlide3__WaitUntilLow();

/*========================================================================*\
   Use :SwitchSlide2
       :Macro function declarations
\*========================================================================*/
#define FCV_01502_SwitchSlide2__POLARITY (0)

MX_UINT8 FCD_01502_SwitchSlide2__ReadState();
void FCD_01502_SwitchSlide2__WaitUntilHigh();
void FCD_01502_SwitchSlide2__SetState(MX_BOOL FCL_STATE);
void FCD_01502_SwitchSlide2__WaitUntilLow();

/*========================================================================*\
   Use :SwitchSlide1
       :Macro function declarations
\*========================================================================*/
#define FCV_01501_SwitchSlide1__POLARITY (0)

MX_UINT8 FCD_01501_SwitchSlide1__ReadState();
void FCD_01501_SwitchSlide1__WaitUntilHigh();
void FCD_01501_SwitchSlide1__SetState(MX_BOOL FCL_STATE);
void FCD_01501_SwitchSlide1__WaitUntilLow();

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02576_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02576_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02576_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02576_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02576_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02576_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02576_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02576_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :TypeConversionsFree
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02575_TypeConversionsFree__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02575_TypeConversionsFree__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02575_TypeConversionsFree__GetFloat();
MX_UINT32 FCD_02575_TypeConversionsFree__GetLong();
MX_UINT16 FCD_02575_TypeConversionsFree__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02575_TypeConversionsFree__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02575_TypeConversionsFree__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02575_TypeConversionsFree__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02574_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02574_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02574_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02574_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02574_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02574_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02574_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02574_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :cal_uart
       :Macro function declarations
\*========================================================================*/
#define MX_UART_UseTX_2 (1)
#define MX_UART_TX_TRIS_2 trisa
#define MX_UART_REF2 
#define MX_UART_RTS_PIN_2 (2)
#define MX_UART_DBITS_2 (8)
#define MX_UART_RETURN_2 (1)
#define MX_UART_RX_PORT_2 porta
#define MX_UART_RTS_PORT_2 portb
#define MX_UART_ECHO_2 (0)
#define MX_UART_FLOWEN_2 (0)
#define MX_UART_CTS_PORT_2 portb
#define MX_UART_TX_PIN_2 (1)
#define MX_UART_RX_TRIS_2 trisa
#define MX_UART_BAUD_2 (115200)
#define MX_UART_RTS_TRIS_2 trisb
#define MX_UART_TX_PORT_2 porta
#define MX_UART_RX_PIN_2 (3)
#define MX_UART_UseRX_2 (1)
#define MX_UART_CTS_TRIS_2 trisb
#define MX_UART_CHANNEL_2 (1)
#define MX_UART_INT_2 (0)
#define MX_UART_CTS_PIN_2 (1)

MX_UINT8 FCD_05482_cal_uart__ControlPin(MX_UINT8 FCL_PIN, MX_UINT8 FCL_STATE);
void FCD_05482_cal_uart__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCD_05482_cal_uart__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR);
void FC_CAL_UART_UpdateBaud_2(MX_UINT8 FCL_NEW_BAUD);
MX_UINT8 FCD_05482_cal_uart__TestProperty(MX_UINT8 FCL_PROPERTY);
void FCD_05482_cal_uart__SendNumber(MX_SINT32 FCL_NUMBER);
void FCD_05482_cal_uart__Prv_SimShowWaveform(MX_UINT8 FCL_TXRX, MX_UINT16 FCL_DATA);
MX_SINT16 FC_CAL_UART_Receive_2(MX_UINT8 FCL_TIMEOUT);
void FC_CAL_UART_Send_2(MX_UINT16 FCL_CHAR);
void FCD_05482_cal_uart__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FC_CAL_UART_Init_2();
void FC_CAL_UART_Delay_2();
void FC_CAL_UART_Uninit_2();
MX_UINT8 FCD_05482_cal_uart__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
MX_UINT8 FCD_05482_cal_uart__ReceiveString(MX_CHAR *FCL_STRINGDATA, MX_UINT16 FCLsz_STRINGDATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
void FCD_047b2_UART_ProgDebug__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
MX_UINT8 FCD_047b2_UART_ProgDebug__ReceiveINTArray(MX_UINT16 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMVALUES, MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
MX_SINT32 FCD_047b2_UART_ProgDebug__ReceiveNumber(MX_UINT8 FCL_TIMEOUT, MX_BOOL FCL_IGNOREDATA);
void FCD_047b2_UART_ProgDebug__SendBinary16Bit(MX_UINT16 FCL_VALUE, MX_BOOL FCL_MSBFIRST);
void FCD_047b2_UART_ProgDebug__SendINTArray(MX_UINT16 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMVALUES, MX_BOOL FCL_MSBFIRST);
void FCD_047b2_UART_ProgDebug__SendNumber(MX_SINT32 FCL_NUMBER);
MX_UINT32 FCD_047b2_UART_ProgDebug__ReceiveBinary32Bit(MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
MX_FLOAT FCD_047b2_UART_ProgDebug__ReceiveBinaryFloat(MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
void FCD_047b2_UART_ProgDebug__SendChar(MX_SINT16 FCL_CHAR);
void FCD_047b2_UART_ProgDebug__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
MX_UINT16 FCD_047b2_UART_ProgDebug__ReceiveBinary16Bit(MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
void FCD_047b2_UART_ProgDebug__ChangeHWBaud(MX_UINT8 FCL_NEWBAUD);
MX_FLOAT FCD_047b2_UART_ProgDebug__ReceiveFloat(MX_UINT8 FCL_TIMEOUT, MX_BOOL FCL_IGNOREDATA);
void FCD_047b2_UART_ProgDebug__SendFloat(MX_FLOAT FCL_NUMBER);
void FCD_047b2_UART_ProgDebug__SendHexNumber(MX_UINT32 FCL_NUMBER, MX_UINT8 FCL_NUMCHARS, MX_BOOL FCL_PREFIX);
MX_UINT32 FCD_047b2_UART_ProgDebug__ReceiveHexNumber(MX_UINT8 FCL_TIMEOUT, MX_BOOL FCL_IGNOREDATA, MX_BOOL FCL_PREFIX);
void FCD_047b2_UART_ProgDebug__SendBinary32Bit(MX_UINT32 FCL_VALUE, MX_BOOL FCL_MSBFIRST);
void FCD_047b2_UART_ProgDebug__SendBinaryFloat(MX_FLOAT FCL_VALUE, MX_BOOL FCL_MSBFIRST);
MX_UINT8 FCD_047b2_UART_ProgDebug__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
void FCD_047b2_UART_ProgDebug__ReceiveString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT8 FCL_TIMEOUT, MX_UINT16 FCL_NUMBYTES);
void FCD_047b2_UART_ProgDebug__Initialise();
MX_SINT16 FCD_047b2_UART_ProgDebug__ReceiveChar(MX_UINT8 FCL_TIMEOUT);

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02573_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02573_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02573_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02573_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02573_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02573_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02573_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02573_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :TypeConversionsFree
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02572_TypeConversionsFree__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02572_TypeConversionsFree__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02572_TypeConversionsFree__GetFloat();
MX_UINT32 FCD_02572_TypeConversionsFree__GetLong();
MX_UINT16 FCD_02572_TypeConversionsFree__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02572_TypeConversionsFree__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02572_TypeConversionsFree__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02572_TypeConversionsFree__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :TypeConversionsFree1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversionsFree1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_02571_TypeConversionsFree1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_02571_TypeConversionsFree1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_02571_TypeConversionsFree1__GetFloat();
MX_UINT32 FCD_02571_TypeConversionsFree1__GetLong();
MX_UINT16 FCD_02571_TypeConversionsFree1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_02571_TypeConversionsFree1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_02571_TypeConversionsFree1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :cal_uart
       :Macro function declarations
\*========================================================================*/
#define MX_UART_UseTX_1 (1)
#define MX_UART_TX_TRIS_1 trisa
#define MX_UART_REF1 
#define MX_UART_RTS_PIN_1 (2)
#define MX_UART_DBITS_1 (8)
#define MX_UART_RETURN_1 (1)
#define MX_UART_RX_PORT_1 porta
#define MX_UART_RTS_PORT_1 portb
#define MX_UART_ECHO_1 (0)
#define MX_UART_FLOWEN_1 (0)
#define MX_UART_CTS_PORT_1 portb
#define MX_UART_TX_PIN_1 (17)
#define MX_UART_RX_TRIS_1 trisa
#define MX_UART_BAUD_1 (1000000)
#define MX_UART_RTS_TRIS_1 trisb
#define MX_UART_TX_PORT_1 porta
#define MX_UART_RX_PIN_1 (16)
#define MX_UART_UseRX_1 (1)
#define MX_UART_CTS_TRIS_1 trisb
#define MX_UART_CHANNEL_1 (2)
#define MX_UART_INT_1 (0)
#define MX_UART_CTS_PIN_1 (1)


/*=----------------------------------------------------------------------=*\
   Use :cal_uart
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_UART_2_REMAPPABLE
#define MX_UART_2_TX_RPOR 17
#define MX_UART_2_TX_UTX 1
#define MX_UART_2_RX_RPINR U2
#define MX_UART_2_RX_RP 16

MX_UINT8 FCD_05481_cal_uart__ControlPin(MX_UINT8 FCL_PIN, MX_UINT8 FCL_STATE);
void FCD_05481_cal_uart__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
void FCD_05481_cal_uart__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR);
void FC_CAL_UART_UpdateBaud_1(MX_UINT8 FCL_NEW_BAUD);
MX_UINT8 FCD_05481_cal_uart__TestProperty(MX_UINT8 FCL_PROPERTY);
void FCD_05481_cal_uart__SendNumber(MX_SINT32 FCL_NUMBER);
void FCD_05481_cal_uart__Prv_SimShowWaveform(MX_UINT8 FCL_TXRX, MX_UINT16 FCL_DATA);
MX_SINT16 FC_CAL_UART_Receive_1(MX_UINT8 FCL_TIMEOUT);
void FC_CAL_UART_Send_1(MX_UINT16 FCL_CHAR);
void FCD_05481_cal_uart__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
void FC_CAL_UART_Init_1();
void FC_CAL_UART_Delay_1();
void FC_CAL_UART_Uninit_1();
MX_UINT8 FCD_05481_cal_uart__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
MX_UINT8 FCD_05481_cal_uart__ReceiveString(MX_CHAR *FCL_STRINGDATA, MX_UINT16 FCLsz_STRINGDATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
void FCD_047b1_UART_ServoBus__SendString(MX_CHAR *FCL_DATA, MX_UINT16 FCLsz_DATA);
MX_UINT8 FCD_047b1_UART_ServoBus__ReceiveINTArray(MX_UINT16 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMVALUES, MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
MX_SINT32 FCD_047b1_UART_ServoBus__ReceiveNumber(MX_UINT8 FCL_TIMEOUT, MX_BOOL FCL_IGNOREDATA);
void FCD_047b1_UART_ServoBus__SendBinary16Bit(MX_UINT16 FCL_VALUE, MX_BOOL FCL_MSBFIRST);
void FCD_047b1_UART_ServoBus__SendINTArray(MX_UINT16 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMVALUES, MX_BOOL FCL_MSBFIRST);
void FCD_047b1_UART_ServoBus__SendNumber(MX_SINT32 FCL_NUMBER);
MX_UINT32 FCD_047b1_UART_ServoBus__ReceiveBinary32Bit(MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
MX_FLOAT FCD_047b1_UART_ServoBus__ReceiveBinaryFloat(MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
void FCD_047b1_UART_ServoBus__SendChar(MX_SINT16 FCL_CHAR);
void FCD_047b1_UART_ServoBus__SendByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES);
MX_UINT16 FCD_047b1_UART_ServoBus__ReceiveBinary16Bit(MX_BOOL FCL_MSBFIRST, MX_UINT8 FCL_TIMEOUT);
void FCD_047b1_UART_ServoBus__ChangeHWBaud(MX_UINT8 FCL_NEWBAUD);
MX_FLOAT FCD_047b1_UART_ServoBus__ReceiveFloat(MX_UINT8 FCL_TIMEOUT, MX_BOOL FCL_IGNOREDATA);
void FCD_047b1_UART_ServoBus__SendFloat(MX_FLOAT FCL_NUMBER);
void FCD_047b1_UART_ServoBus__SendHexNumber(MX_UINT32 FCL_NUMBER, MX_UINT8 FCL_NUMCHARS, MX_BOOL FCL_PREFIX);
MX_UINT32 FCD_047b1_UART_ServoBus__ReceiveHexNumber(MX_UINT8 FCL_TIMEOUT, MX_BOOL FCL_IGNOREDATA, MX_BOOL FCL_PREFIX);
void FCD_047b1_UART_ServoBus__SendBinary32Bit(MX_UINT32 FCL_VALUE, MX_BOOL FCL_MSBFIRST);
void FCD_047b1_UART_ServoBus__SendBinaryFloat(MX_FLOAT FCL_VALUE, MX_BOOL FCL_MSBFIRST);
MX_UINT8 FCD_047b1_UART_ServoBus__ReceiveByteArray(MX_UINT8 *FCL_DATA, MX_UINT16 FCLsz_DATA, MX_UINT16 FCL_NUMBYTES, MX_UINT8 FCL_TIMEOUT);
void FCD_047b1_UART_ServoBus__ReceiveString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL, MX_UINT8 FCL_TIMEOUT, MX_UINT16 FCL_NUMBYTES);
void FCD_047b1_UART_ServoBus__Initialise();
MX_SINT16 FCD_047b1_UART_ServoBus__ReceiveChar(MX_UINT8 FCL_TIMEOUT);

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_1 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_7 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_2 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_2 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_2 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_2();
void FC_ADC_Enable_2(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_2(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT16 FCD_0cc52_adc_base1__RawSampleInt();
MX_UINT8 FCD_0cc52_adc_base1__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_0cc52_adc_base1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_0cc52_adc_base1__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_0cc52_adc_base1__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_0cc52_adc_base1__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_0cc52_adc_base1__GetVoltage();
void FCD_0cc52_adc_base1__RawEnable();
MX_UINT8 FCD_0cc52_adc_base1__RawSampleByte();
MX_UINT16 FCD_0cc52_adc_base1__GetInt();
void FCD_0cc52_adc_base1__RawDisable();
MX_UINT8 FCD_0cc52_adc_base1__GetByte();
MX_UINT32 FCD_0c432_MapFunction1__MapUlong(MX_UINT32 FCL_VALUE, MX_UINT32 FCL_INMIN, MX_UINT32 FCL_INMAX, MX_UINT32 FCL_OUTMIN, MX_UINT32 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_SINT16 FCD_0c432_MapFunction1__MapInt(MX_SINT16 FCL_VALUE, MX_SINT16 FCL_INMIN, MX_SINT16 FCL_INMAX, MX_SINT16 FCL_OUTMIN, MX_SINT16 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_FLOAT FCD_0c432_MapFunction1__MapFloat(MX_FLOAT FCL_VALUE, MX_FLOAT FCL_INMIN, MX_FLOAT FCL_INMAX, MX_FLOAT FCL_OUTMIN, MX_FLOAT FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_SINT32 FCD_0c432_MapFunction1__MapLong(MX_SINT32 FCL_VALUE, MX_SINT32 FCL_INMIN, MX_SINT32 FCL_INMAX, MX_SINT32 FCL_OUTMIN, MX_SINT32 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_UINT16 FCD_0c432_MapFunction1__MapUInt(MX_UINT16 FCL_VALUE, MX_UINT16 FCL_INMIN, MX_UINT16 FCL_INMAX, MX_UINT16 FCL_OUTMIN, MX_UINT16 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_UINT8 FCD_0c432_MapFunction1__MapByte(MX_UINT8 FCL_VALUE, MX_UINT8 FCL_INMIN, MX_UINT8 FCL_INMAX, MX_UINT8 FCL_OUTMIN, MX_UINT8 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_BOOL FCD_0b4c2_IsSim1__Check();

/*========================================================================*\
   Use :ADC1
       :Macro function declarations
\*========================================================================*/
#define FCV_07042_ADC1__COMPONENTLABEL (0)

void FCD_07042_ADC1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_07042_ADC1__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_07042_ADC1__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_07042_ADC1__GetVoltage();
MX_UINT16 FCD_07042_ADC1__GetInt();
MX_UINT8 FCD_07042_ADC1__GetByte();

/*========================================================================*\
   Use :cal_adc
       :Macro function declarations
\*========================================================================*/
#define MX_ADC_REF1 
#define MX_ADC_TYPE_1 
#define MX_ADC_BITS_12 
#define MX_ADC_CHANNEL_6 


/*=----------------------------------------------------------------------=*\
   Use :cal_adc
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define FC_ADC_Enable_1 FC_CAL_ADC_Enable_1
#define FC_ADC_Disable_1 FC_CAL_ADC_Disable_1
#define FC_ADC_Sample_1 FC_CAL_ADC_Sample_1

void FC_ADC_Disable_1();
void FC_ADC_Enable_1(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_CONV_SPEED, MX_UINT8 FCL_VREF, MX_UINT8 FCL_T_CHARGE);
MX_UINT16 FC_ADC_Sample_1(MX_UINT8 FCL_SAMPLE_MODE);
MX_UINT16 FCD_0cc51_adc_base1__RawSampleInt();
MX_UINT8 FCD_0cc51_adc_base1__RawAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
void FCD_0cc51_adc_base1__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_0cc51_adc_base1__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_SINT16 FCD_0cc51_adc_base1__RawAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_0cc51_adc_base1__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_0cc51_adc_base1__GetVoltage();
void FCD_0cc51_adc_base1__RawEnable();
MX_UINT8 FCD_0cc51_adc_base1__RawSampleByte();
MX_UINT16 FCD_0cc51_adc_base1__GetInt();
void FCD_0cc51_adc_base1__RawDisable();
MX_UINT8 FCD_0cc51_adc_base1__GetByte();
MX_UINT32 FCD_0c431_MapFunction1__MapUlong(MX_UINT32 FCL_VALUE, MX_UINT32 FCL_INMIN, MX_UINT32 FCL_INMAX, MX_UINT32 FCL_OUTMIN, MX_UINT32 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_SINT16 FCD_0c431_MapFunction1__MapInt(MX_SINT16 FCL_VALUE, MX_SINT16 FCL_INMIN, MX_SINT16 FCL_INMAX, MX_SINT16 FCL_OUTMIN, MX_SINT16 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_FLOAT FCD_0c431_MapFunction1__MapFloat(MX_FLOAT FCL_VALUE, MX_FLOAT FCL_INMIN, MX_FLOAT FCL_INMAX, MX_FLOAT FCL_OUTMIN, MX_FLOAT FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_SINT32 FCD_0c431_MapFunction1__MapLong(MX_SINT32 FCL_VALUE, MX_SINT32 FCL_INMIN, MX_SINT32 FCL_INMAX, MX_SINT32 FCL_OUTMIN, MX_SINT32 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_UINT16 FCD_0c431_MapFunction1__MapUInt(MX_UINT16 FCL_VALUE, MX_UINT16 FCL_INMIN, MX_UINT16 FCL_INMAX, MX_UINT16 FCL_OUTMIN, MX_UINT16 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_UINT8 FCD_0c431_MapFunction1__MapByte(MX_UINT8 FCL_VALUE, MX_UINT8 FCL_INMIN, MX_UINT8 FCL_INMAX, MX_UINT8 FCL_OUTMIN, MX_UINT8 FCL_OUTMAX, MX_BOOL FCL_CLAMPMINMAX);
MX_BOOL FCD_0b4c1_IsSim1__Check();

/*========================================================================*\
   Use :ADC0
       :Macro function declarations
\*========================================================================*/
#define FCV_07041_ADC0__COMPONENTLABEL (0)

void FCD_07041_ADC0__GetString(MX_CHAR *FCR_RETVAL, MX_UINT16 FCRsz_RETVAL);
MX_UINT8 FCD_07041_ADC0__GetAverageByte(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_UINT16 FCD_07041_ADC0__GetAverageInt(MX_UINT8 FCL_NUMSAMPLES, MX_UINT8 FCL_DELAYUS);
MX_FLOAT FCD_07041_ADC0__GetVoltage();
MX_UINT16 FCD_07041_ADC0__GetInt();
MX_UINT8 FCD_07041_ADC0__GetByte();

/*========================================================================*\
   Use :TypeConversions1
       :Macro function declarations
\*========================================================================*/

/*=----------------------------------------------------------------------=*\
   Use :TypeConversions1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/

#ifndef MX_UNIONTYPE
 #define MX_UNIONTYPE
 typedef union
{
  MX_FLOAT AsFloat;
  MX_UINT32 AsLong;
  MX_UINT16 AsInt[2];
  MX_UINT8  AsByte[4];
} MX_Union_Type;
 MX_Union_Type MX_Conv_Var;
#endif


void FCD_08941_TypeConversions1__SetInt(MX_UINT8 FCL_INDEX, MX_UINT16 FCL_VALUE);
void FCD_08941_TypeConversions1__SetLong(MX_UINT32 FCL_VALUE);
MX_FLOAT FCD_08941_TypeConversions1__GetFloat();
MX_UINT32 FCD_08941_TypeConversions1__GetLong();
void FCD_08941_TypeConversions1__SetBytes(MX_UINT8 FCL_BYTE0, MX_UINT8 FCL_BYTE1, MX_UINT8 FCL_BYTE2, MX_UINT8 FCL_BYTE3);
MX_UINT16 FCD_08941_TypeConversions1__GetInt(MX_UINT8 FCL_INDEX);
void FCD_08941_TypeConversions1__SetByte(MX_UINT8 FCL_INDEX, MX_UINT8 FCL_VALUE);
MX_UINT8 FCD_08941_TypeConversions1__GetByte(MX_UINT8 FCL_INDEX);
void FCD_08941_TypeConversions1__SetFloat(MX_FLOAT FCL_VALUE);

/*========================================================================*\
   Use :cal_spi1
       :Macro function declarations
\*========================================================================*/
#define MX_SPI_SS_TRIS_1 trisa
#define MX_SPI_MISO_PORT_1 porta
#define MX_SPI_SCK_TRIS_1 trisa
#define MX_SPI_SCK_PIN_1 (14)
#define MX_SPI_MOSI_TRIS_1 trisa
#define MX_SPI_BMODE_1 (0)
#define MX_SPI_MISO_TRIS_1 trisa
#define MX_SPI_MOSI_PIN_1 (12)
#define MX_SPI_MISO_PIN_1 (13)
#define MX_SPI_SS_PIN_1 (15)
#define MX_SPI_PR_SCALE_1 2000000
#define MX_SPI_SS_PORT_1 porta
#define MX_SPI_USESS_1 0
#define MX_SPI_SCK_PORT_1 porta
#define MX_SPI_MOSI_PORT_1 porta
#define MX_SPI_CHANNEL_1 (1)


/*=----------------------------------------------------------------------=*\
   Use :cal_spi1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_SPI_REF1
#define MX_SPI_REMAPPABLE_1 1
#define MX_SPI_MOSI_RPOR_1 12
#define MX_SPI_MOSI_SDO_1 1
#define MX_SPI_MISO_RPINR_1 SPI1
#define MX_SPI_MISO_RP_1 13
#define MX_SPI_CLK_RPOR_1 14
#define MX_SPI_CLK_SCK_1 1

void FCD_01531_cal_spi1__Master_Enable_CS();
void FC_CAL_SPI_Slave_Uninit_1();
void FCD_01531_cal_spi1__Prv_TextConsole(MX_CHAR *FCL_STR, MX_UINT16 FCLsz_STR, MX_UINT8 FCL_COLOUR, MX_UINT8 FCL_APPENDTIMESTAMP);
MX_UINT8 FC_CAL_SPI_Transaction_1(MX_UINT8 *FCL_BUFFER, MX_UINT16 FCLsz_BUFFER, MX_UINT16 FCL_LENGTH);
void FCD_01531_cal_spi1__Prv_SimShowWaveform(MX_UINT8 FCL_RXDATA, MX_UINT16 FCL_TXDATA);
void FC_CAL_SPI_Slave_Init_1();
void FCD_01531_cal_spi1__Master_Disable_CS();
void FC_CAL_SPI_Master_Uninit_1();
MX_UINT8 FC_CAL_SPI_Master_Byte_1(MX_UINT8 FCL_DATAOUT);
void FC_CAL_SPI_Slave_TxByte_1(MX_UINT8 FCL_DATA);
MX_UINT8 FC_CAL_SPI_Slave_RxByte_1();
MX_UINT8 FC_CAL_SPI_Master_Init_1();
void FCD_0ff31_ADS1220__WriteConfigRegisters();
MX_FLOAT FCD_0ff31_ADS1220__SampleDiffVolts(MX_UINT8 FCL_CHANNELA, MX_UINT8 FCL_CHANNELB, MX_UINT8 FCL_GAIN);
MX_SINT32 FCD_0ff31_ADS1220__ReadSample();
MX_FLOAT FCD_0ff31_ADS1220__ReadRTDResistance();
MX_SINT32 FCD_0ff31_ADS1220__SampleSglRaw(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_GAIN);
MX_FLOAT FCD_0ff31_ADS1220__ReadRTDTemperature();
MX_FLOAT FCD_0ff31_ADS1220__SampleSglVolts(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_GAIN);
MX_SINT32 FCD_0ff31_ADS1220__SampleDiffRAW(MX_UINT8 FCL_CHANNELA, MX_UINT8 FCL_CHANNELB, MX_UINT8 FCL_GAIN);
MX_UINT8 FCD_0ff31_ADS1220__Initialise();

/*========================================================================*\
   Use :cal_pwm
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE3 (1)
#define MX_PWM_PIN_3 (23)
#define MX_PWM_TYPE_3 (0)
#define MX_PWM_PORT_3 PORTA
#define MX_PWM_TRIS_3 TRISA
#define MX_PWM_CHANNEL_3 (11)


/*=----------------------------------------------------------------------=*\
   Use :cal_pwm
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF3

#define MX_PWM_FREQ_3  1068
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_3 23
#define MX_PWM_RPOC_3 11
#define MX_PWM_TMR_3 0

void FC_CAL_PWM_ChangePeriod_3(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_3();
void FC_CAL_PWM_SetDuty8Bit_3(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_3();
void FC_CAL_PWM_ChangeFrequency_3(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_3(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_3(MX_FLOAT FCL_DUTY);
void FCD_0df43_PWM2__ChangePeriod(MX_UINT16 FCL_PERIOD, MX_SINT16 FCL_PRESCALER);
void FCD_0df43_PWM2__Disable();
void FCD_0df43_PWM2__SetDutyCycle(MX_UINT8 FCL_DUTY);
void FCD_0df43_PWM2__Enable();
void FCD_0df43_PWM2__SetFrequency(MX_UINT32 FCL_FREQUENCY);
void FCD_0df43_PWM2__SetDutyCycle10Bit(MX_UINT16 FCL_DUTY);

/*========================================================================*\
   Use :cal_pwm
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE2 (1)
#define MX_PWM_PIN_2 (22)
#define MX_PWM_TYPE_2 (0)
#define MX_PWM_PORT_2 PORTA
#define MX_PWM_TRIS_2 TRISA
#define MX_PWM_CHANNEL_2 (10)


/*=----------------------------------------------------------------------=*\
   Use :cal_pwm
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF2

#define MX_PWM_FREQ_2  1068
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_2 22
#define MX_PWM_RPOC_2 10
#define MX_PWM_TMR_2 0

void FC_CAL_PWM_ChangePeriod_2(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_2();
void FC_CAL_PWM_SetDuty8Bit_2(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_2();
void FC_CAL_PWM_ChangeFrequency_2(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_2(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_2(MX_FLOAT FCL_DUTY);
void FCD_0df42_PWM1__ChangePeriod(MX_UINT16 FCL_PERIOD, MX_SINT16 FCL_PRESCALER);
void FCD_0df42_PWM1__Disable();
void FCD_0df42_PWM1__SetDutyCycle(MX_UINT8 FCL_DUTY);
void FCD_0df42_PWM1__Enable();
void FCD_0df42_PWM1__SetFrequency(MX_UINT32 FCL_FREQUENCY);
void FCD_0df42_PWM1__SetDutyCycle10Bit(MX_UINT16 FCL_DUTY);

/*========================================================================*\
   Use :Servo_Controller1
       :Macro function declarations
\*========================================================================*/
#define MX_SERVO_CCPR1H 234
#define MX_SERVO_CCPR1L 216
#define MX_Servo_Channel_Count 1


/*=----------------------------------------------------------------------=*\
   Use :Servo_Controller1
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#ifdef MX_CAL_PIC

	#define MX_SERVO_REG_CCPR1H		CCPR1H
	#define MX_SERVO_REG_CCPR1L		CCPR1L
	#define MX_SERVO_REG_CCPR2H		CCPR2H
	#define MX_SERVO_REG_CCPR2L		CCPR2L
	#define MX_SERVO_REG_T1CON		T1CON
	#define MX_SERVO_REG_CCP1CON	CCP1CON
	#define MX_SERVO_REG_CCP2CON 	CCP2CON
	#define MX_SERVO_T1CON			0x01

#ifdef _PIE6_CCP1IE_POSN
	#define MX_SERVO_REG_CCP1EN		PIE6
	#define MX_SERVO_REG_CCP1F		PIR6
	#define MX_SERVO_REG_CCP2EN		PIE6
	#define MX_SERVO_REG_CCP2F		PIR6
	#define MX_SERVO_CCP1CON	    0x8b
	#define MX_SERVO_CCP2CON	    0x8a
    #define MX_SERVO_T1_CLK         0x01
#else
  #ifdef _PIE3_CCP1IE_POSN
	#define MX_SERVO_REG_CCP1EN		PIE3
	#define MX_SERVO_REG_CCP1F		PIR3
	#define MX_SERVO_REG_CCP2EN		PIE3
	#define MX_SERVO_REG_CCP2F		PIR3
	#define MX_SERVO_CCP1CON	    0x0b
	#define MX_SERVO_CCP2CON	    0x0a
  #else
    #ifdef _PIE4_CCP1IE_POSN
	    #define MX_SERVO_REG_CCP1EN		PIE4
	    #define MX_SERVO_REG_CCP1F		PIR4
	    #define MX_SERVO_REG_CCP2EN		PIE4
	    #define MX_SERVO_REG_CCP2F		PIR4
	    #define MX_SERVO_CCP1CON	    0x8b
	    #define MX_SERVO_CCP2CON	    0x8a
    #else
      #ifdef _PIE7_CCP1IE_POSN
	      #define MX_SERVO_REG_CCP1EN	PIE7
	      #define MX_SERVO_REG_CCP1F	PIR7
	      #define MX_SERVO_REG_CCP2EN	PIE7
	      #define MX_SERVO_REG_CCP2F	PIR7
	      #define MX_SERVO_CCP1CON	    0x8b
	      #define MX_SERVO_CCP2CON	    0x8a
	      #define MX_SERVO_T1_CLK         0x01
      #else
	      #define MX_SERVO_REG_CCP1EN	PIE1
	      #define MX_SERVO_REG_CCP1F	PIR1
	      #define MX_SERVO_REG_CCP2EN	PIE2
	      #define MX_SERVO_REG_CCP2F	PIR2
	      #define MX_SERVO_CCP1CON	    0x0b
	      #define MX_SERVO_CCP2CON	    0x0a
      #endif
    #endif
  #endif
#endif

#ifndef INTCON
	#define INTCON	INTCON0
#endif
	#define MX_SERVO_FLAG_CCP1EN		CCP1IE
	#define MX_SERVO_FLAG_CCP2EN		CCP2IE
	#define MX_SERVO_FLAG_CCP1F			CCP1IF
	#define MX_SERVO_FLAG_CCP2F			CCP2IF
	#define MX_SERVO_REG_INT			INTCON
	#define MX_SERVO_FLAG_GLOB			GIE
	#define MX_SERVO_FLAG_PERIPH		PEIE

	#define MX_CCP1_INT_START		if (ts_bit(MX_SERVO_REG_CCP1F, MX_SERVO_FLAG_CCP1F) && ts_bit(MX_SERVO_REG_CCP1EN, MX_SERVO_FLAG_CCP1EN))
	#define MX_CCP2_INT_START		if (ts_bit(MX_SERVO_REG_CCP2F, MX_SERVO_FLAG_CCP2F) && ts_bit(MX_SERVO_REG_CCP2EN, MX_SERVO_FLAG_CCP2EN))

#endif

#ifdef MX_CAL_PIC16

	#define MX_SERVO_REG_CCP1F		IFS0bits
	#define MX_SERVO_FLAG_CCP1F		T3IF

	#define MX_SERVO_REG_CCP2F		IFS0bits
	#define MX_SERVO_FLAG_CCP2F		T2IF

	#define MX_CCP1_INT_START		void _ISR _T3Interrupt(void)
	#define MX_CCP2_INT_START		void _ISR _T2Interrupt(void)

#endif

#ifdef MX_CAL_AVR

	MX_UINT8	mx_servo_dummy;

	#ifdef MX_XMEGA

		#define OCR1AL	TCC1.CCA
		#define OCR1BL	TCC1.CCB
		#define TCCR1A	TCC1.CTRLA
		#define TCCR1B	TCC1.CTRLB
		#define TIMSK1	TCC1.INTCTRLB
		#define TIFR1	TCC1.INTFLAGS
		#define OCF1A	4
		#define OCF1B	5
		#define OCIE1A	0
		#define OCIE1B	2

	#else

		#ifndef TIMSK1
			#ifdef TIMSK
				#define TIMSK1	TIMSK
			#endif
		#endif

		#ifndef TIFR1
			#ifdef TIFR
				#define TIFR1	TIFR
			#endif
		#endif

		#ifndef OCR1AH
			#ifdef OCR1A
				#define OCR1AH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1AL
			#ifdef OCR1A
				#define OCR1AL	OCR1A
			#endif
		#endif

		#ifndef OCR1BH
			#ifdef OCR1B
				#define OCR1BH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1BL
			#ifdef OCR1B
				#define OCR1BL	TCC1.CCB
			#endif
		#endif

	#endif

	#define MX_SERVO_T1CON		0x01

	#define MX_SERVO_REG_CCPR1H		OCR1AH
	#define MX_SERVO_REG_CCPR1L		OCR1AL
	#define MX_SERVO_REG_CCPR2H		OCR1BH
	#define MX_SERVO_REG_CCPR2L		OCR1BL
	#define MX_SERVO_REG_T1CON		mx_servo_dummy
	#define MX_SERVO_REG_CCP1CON	TCCR1A
	#define MX_SERVO_REG_CCP2CON 	TCCR1B
	#define MX_SERVO_REG_CCP1EN		TIMSK1
	#define MX_SERVO_REG_CCP2EN		TIMSK1
	#define MX_SERVO_FLAG_CCP1EN	OCIE1A
	#define MX_SERVO_FLAG_CCP2EN	OCIE1B
	#define MX_SERVO_REG_CCP1F		TIFR1
	#define MX_SERVO_REG_CCP2F		TIFR1
	#define MX_SERVO_FLAG_CCP1F		OCF1A
	#define MX_SERVO_FLAG_CCP2F		OCF1B
	#define MX_SERVO_REG_INT		mx_servo_dummy
	#define MX_SERVO_FLAG_GLOB		0
	#define MX_SERVO_FLAG_PERIPH	0

	#define MX_SERVO_CCP1CON	0x00
	#define MX_SERVO_CCP2CON	0x09	//CTC mode with PWM prescale / 8

	#define MX_CCP1_INT_START		ISR(TIMER1_COMPA_vect)
	#define MX_CCP2_INT_START		ISR(TIMER1_COMPB_vect)

#endif

#ifdef MX_CAL_ARD

	MX_UINT8	mx_servo_dummy;

	#ifdef MX_XMEGA

		#define OCR1AL	TCC1.CCA
		#define OCR1BL	TCC1.CCB
		#define TCCR1A	TCC1.CTRLA
		#define TCCR1B	TCC1.CTRLB
		#define TIMSK1	TCC1.INTCTRLB
		#define TIFR1	TCC1.INTFLAGS
		#define OCF1A	4
		#define OCF1B	5
		#define OCIE1A	0
		#define OCIE1B	2

	#else

		#ifndef TIMSK1
			#ifdef TIMSK
				#define TIMSK1	TIMSK
			#endif
		#endif

		#ifndef TIFR1
			#ifdef TIFR
				#define TIFR1	TIFR
			#endif
		#endif

		#ifndef OCR1AH
			#ifdef OCR1A
				#define OCR1AH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1AL
			#ifdef OCR1A
				#define OCR1AL	OCR1A
			#endif
		#endif

		#ifndef OCR1BH
			#ifdef OCR1B
				#define OCR1BH	mx_servo_dummy
			#endif
		#endif

		#ifndef OCR1BL
			#ifdef OCR1B
				#define OCR1BL	TCC1.CCB
			#endif
		#endif

	#endif

	#define MX_SERVO_T1CON		0x01

	#define MX_SERVO_REG_CCPR1H		OCR1AH
	#define MX_SERVO_REG_CCPR1L		OCR1AL
	#define MX_SERVO_REG_CCPR2H		OCR1BH
	#define MX_SERVO_REG_CCPR2L		OCR1BL
	#define MX_SERVO_REG_T1CON		mx_servo_dummy
	#define MX_SERVO_REG_CCP1CON	TCCR1A
	#define MX_SERVO_REG_CCP2CON 	TCCR1B
	#define MX_SERVO_REG_CCP1EN		TIMSK1
	#define MX_SERVO_REG_CCP2EN		TIMSK1
	#define MX_SERVO_FLAG_CCP1EN	OCIE1A
	#define MX_SERVO_FLAG_CCP2EN	OCIE1B
	#define MX_SERVO_REG_CCP1F		TIFR1
	#define MX_SERVO_REG_CCP2F		TIFR1
	#define MX_SERVO_FLAG_CCP1F		OCF1A
	#define MX_SERVO_FLAG_CCP2F		OCF1B
	#define MX_SERVO_REG_INT		mx_servo_dummy
	#define MX_SERVO_FLAG_GLOB		0
	#define MX_SERVO_FLAG_PERIPH	0

	#define MX_SERVO_CCP1CON	0x00
	#define MX_SERVO_CCP2CON	0x09	//CTC mode with PWM prescale / 8

	#define MX_CCP1_INT_START		ISR(TIMER1_COMPA_vect)
	#define MX_CCP2_INT_START		ISR(TIMER1_COMPB_vect)

#endif

#if defined MX_CAL_STARM

	#define TIM_SERVO_INSTANCE				TIM3
	#define TIM_SERVO_IRQHandler			TIM3_IRQHandler
	#define MX_ISR_TIM_SERVO				MX_ISR_TIM3
	#define __HAL_RCC_TIM_SERVO_CLK_ENABLE	__HAL_RCC_TIM3_CLK_ENABLE
	#define TIM_SERVO_IRQn					TIM3_IRQn

	TIM_HandleTypeDef		MX_HANDLE_TIM_SERVO;
	TIM_OC_InitTypeDef		MX_CONFIG_OC_SERVO;

	#define MX_CCP1_INT_START \
		void TIM_SERVO_IRQHandler(void) \
		{ \
			HAL_TIM_IRQHandler(&(MX_HANDLE_TIM_SERVO)); \
		} \
		void MX_ISR_TIM_SERVO()

	#define MX_CCP2_INT_START		void HAL_TIM_OC_DelayElapsedCallback(TIM_HandleTypeDef *htim)

#elif defined MX_CAL_ARM

	MX_UINT8	mx_servo_dummy;

	#define MX_SERVO_REG_CCP1F		mx_servo_dummy
	#define MX_SERVO_REG_CCP2F		mx_servo_dummy
	#define MX_SERVO_FLAG_CCP1F		0
	#define MX_SERVO_FLAG_CCP2F		1

	#define MX_CCP1_INT_START		if ((periphID == AT91C_ID_TC2) && (IFlags & AT91C_TC_CPCS))
	#define MX_CCP2_INT_START		if ((periphID == AT91C_ID_TC2) && (IFlags & AT91C_TC_CPAS))

#elif defined MX_CAL_ESP

	MX_UINT8	mx_servo_dummy;

	#define MX_SERVO_REG_CCP1F		mx_servo_dummy
	#define MX_SERVO_REG_CCP2F		mx_servo_dummy
	#define MX_SERVO_FLAG_CCP1F		0
	#define MX_SERVO_FLAG_CCP2F		1

	#define MX_CCP1_INT_START		void Servo_Macro_Dummy1 ()
	#define MX_CCP2_INT_START		void Servo_Macro_Dummy2 ()

#endif

//ESP32 CAL PWM Definitions
#define MX_PWM
#define MX_PWM_REF4
#define MX_PWM_CHANNEL_4 1
#define MX_PWM_PORT_4 PORTA
#define MX_PWM_PIN_4 18
#define MX_PWM_FREQ_4 50
#define FC_CAL_PWM_Disable_X1 FC_CAL_PWM_Disable_4
#define FC_CAL_PWM_Enable_X1 FC_CAL_PWM_Enable_4
#define FC_CAL_PWM_SetDutyFloat_X1 FC_CAL_PWM_SetDutyFloat_4

void FCD_0dd21_Servo_Controller1__DisableServo(MX_UINT8 FCL_CHANNEL);
void FCD_0dd21_Servo_Controller1__SetPosition(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_POSITION);
MX_UINT8 FCD_0dd21_Servo_Controller1__MoveToPositionInt(MX_UINT8 FCL_CHANNEL, MX_UINT16 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__SetPositionInt(MX_UINT8 FCL_CHANNEL, MX_UINT16 FCL_POSITION);
MX_BOOL FCD_0dd21_Servo_Controller1__MoveToAngle(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_ANGLE);
MX_UINT8 FCD_0dd21_Servo_Controller1__MoveToPosition(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__SetTrim(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_TRIM);
MX_UINT8 FCD_0dd21_Servo_Controller1__IsAutoMoving();
void FCD_0dd21_Servo_Controller1__SetAutoMoveSpeedInt(MX_UINT16 FCL_SPEED);
MX_UINT8 FCD_0dd21_Servo_Controller1__IsServoAutoMoving(MX_UINT8 FCL_CHANNEL);
void FCD_0dd21_Servo_Controller1__AutoMoveToPosition(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__EnableServo(MX_UINT8 FCL_CHANNEL);
void FCD_0dd21_Servo_Controller1__AutoMoveToAngle(MX_UINT8 FCL_CHANNEL, MX_UINT8 FCL_ANGLE);
void FCD_0dd21_Servo_Controller1__SetAutoMoveSpeed(MX_UINT8 FCL_SPEED);
void FCD_0dd21_Servo_Controller1__AutoMoveToPositionInt(MX_UINT8 FCL_CHANNEL, MX_UINT16 FCL_POSITION);
void FCD_0dd21_Servo_Controller1__Initialise();

/*========================================================================*\
   Use :cal_pwm
       :Macro function declarations
\*========================================================================*/
#define MX_PWM_PRESCALE1 (1)
#define MX_PWM_PIN_1 (3)
#define MX_PWM_TYPE_1 (0)
#define MX_PWM_PORT_1 PORTA
#define MX_PWM_TRIS_1 TRISA
#define MX_PWM_CHANNEL_1 (1)


/*=----------------------------------------------------------------------=*\
   Use :cal_pwm
       :Supplementary defines
\*=----------------------------------------------------------------------=*/
#define MX_PWM
#define MX_PWM_REF1

#define MX_PWM_FREQ_1  50
#define MX_PWM_REMAPPABLE
#define MX_PWM_RPOR_1 3
#define MX_PWM_RPOC_1 1
#define MX_PWM_TMR_1 0

void FC_CAL_PWM_ChangePeriod_1(MX_UINT16 FCL_PERIOD, MX_UINT16 FCL_PRESCALER);
void FC_CAL_PWM_Disable_1();
void FC_CAL_PWM_SetDuty8Bit_1(MX_UINT8 FCL_DUTY);
void FC_CAL_PWM_Enable_1();
void FC_CAL_PWM_ChangeFrequency_1(MX_UINT32 FCL_FREQUENCY);
void FC_CAL_PWM_SetDuty10Bit_1(MX_UINT16 FCL_DUTY);
void FC_CAL_PWM_SetDutyFloat_1(MX_FLOAT FCL_DUTY);
void FCD_0df41_HobbyServoPwm__ChangePeriod(MX_UINT16 FCL_PERIOD, MX_SINT16 FCL_PRESCALER);
void FCD_0df41_HobbyServoPwm__Disable();
void FCD_0df41_HobbyServoPwm__SetDutyCycle(MX_UINT8 FCL_DUTY);
void FCD_0df41_HobbyServoPwm__Enable();
void FCD_0df41_HobbyServoPwm__SetFrequency(MX_UINT32 FCL_FREQUENCY);
void FCD_0df41_HobbyServoPwm__SetDutyCycle10Bit(MX_UINT16 FCL_DUTY);

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"

