#!/bin/bash
#
# Install the ST3215 WebSocket server as a systemd service.
# - Starts automatically on boot
# - Restarts automatically if the process stops (Restart=always)
# - Writes debug logs under /var/log/robot-arm-st3215/
#
# Usage (on the Raspberry Pi):
#   cd /opt/RobotArm/raspberry-pi-control-st3215
#   sudo bash install-service.sh /opt/RobotArm/raspberry-pi-control-st3215
#
# If ./install-service.sh says "command not found", use "sudo bash ..." (Windows CRLF fix).
# Optional: install from a different folder
#   sudo bash install-service.sh /path/to/raspberry-pi-control-st3215
#
# Safe to re-run after "git pull" — fixes /opt permissions, runs npm install,
# refreshes the systemd unit, and restarts the server. Do not run "npm install"
# by hand in /opt unless you use sudo; use this script instead.

set -e

SERVICE_NAME="st3215-server.service"
LOG_DIR="/var/log/robot-arm-st3215"
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -n "$1" ]; then
    INSTALL_DIR="$(cd "$1" && pwd)"
fi

echo "=========================================="
echo "Robot Arm ST3215 server — install service"
echo "=========================================="
echo ""

if [ "$EUID" -ne 0 ]; then
    echo "Error: run this script with sudo"
    echo "  sudo ./install-service.sh"
    exit 1
fi

if [ ! -f "$INSTALL_DIR/server.js" ]; then
    echo "Error: server.js not found in: $INSTALL_DIR"
    exit 1
fi

if [ ! -f "$INSTALL_DIR/st3215-server.service" ]; then
    echo "Error: st3215-server.service not found in: $INSTALL_DIR"
    exit 1
fi

# User that runs the service (the person who used sudo, or pi)
if [ -n "$SUDO_USER" ]; then
    SERVICE_USER="$SUDO_USER"
else
    SERVICE_USER="pi"
fi

if ! id "$SERVICE_USER" &>/dev/null; then
    echo "Error: user '$SERVICE_USER' does not exist."
    exit 1
fi

NODE_PATH="$(command -v node || true)"
if [ -z "$NODE_PATH" ]; then
    echo "Error: node is not installed. Install Node.js first, for example:"
    echo "  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"
    echo "  sudo apt-get install -y nodejs"
    exit 1
fi

echo "Install folder:  $INSTALL_DIR"
echo "Service user:    $SERVICE_USER"
echo "Node:            $NODE_PATH"
echo "Log folder:      $LOG_DIR"
echo ""
echo "(Re-running this script is OK — use it to upgrade after git pull.)"
echo ""

# Serial port group
if getent group dialout >/dev/null; then
    usermod -aG dialout "$SERVICE_USER" 2>/dev/null || true
    echo "  User $SERVICE_USER added to dialout group (serial port access)."
fi

echo "Step 1: Fix folder ownership (needed if files are root-owned under /opt)"
REPO_DIR="$INSTALL_DIR"
while [ "$REPO_DIR" != "/" ]; do
    if [ -d "$REPO_DIR/.git" ]; then
        chown -R "$SERVICE_USER:$SERVICE_USER" "$REPO_DIR"
        sudo -u "$SERVICE_USER" git config --global --add safe.directory "$REPO_DIR" 2>/dev/null || true
        echo "  Git repo owned by $SERVICE_USER: $REPO_DIR"
        break
    fi
    REPO_DIR="$(dirname "$REPO_DIR")"
done
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"
echo "  $INSTALL_DIR owned by $SERVICE_USER"
echo ""

echo "Step 2: npm install"
cd "$INSTALL_DIR"
sudo -u "$SERVICE_USER" npm install
echo "  Done."
echo ""

echo "Step 3: Create log directory"

mkdir -p "$LOG_DIR"
chown "$SERVICE_USER:$SERVICE_USER" "$LOG_DIR"
chmod 755 "$LOG_DIR"
touch "$LOG_DIR/server.log" "$LOG_DIR/server-debug.log"
chown "$SERVICE_USER:$SERVICE_USER" "$LOG_DIR/server.log" "$LOG_DIR/server-debug.log"
echo "  Done."
echo ""

echo "Step 3b: Disable onboard analogue audio (WS2812B status LED needs the PWM clock)"
# led_driver.py drives the WS2812B strip on GPIO18 through PWM0 + DMA via
# rpi_ws281x. The Pi's headphone-jack audio (snd_bcm2835) is generated by the
# firmware on the same PWM block/clock, so the first time anything opens that
# audio device (PipeWire/Chromium playing a UI click) the firmware reprograms
# the PWM clock and the strip freezes on its last frame. HDMI audio is a
# separate device and is unaffected. Takes effect on next reboot.
BOOT_CONFIG="/boot/firmware/config.txt"
[ -f "$BOOT_CONFIG" ] || BOOT_CONFIG="/boot/config.txt"
NEEDS_REBOOT=0
if [ -f "$BOOT_CONFIG" ]; then
    if grep -qE '^\s*dtparam=audio=on' "$BOOT_CONFIG"; then
        sed -i -E 's/^\s*dtparam=audio=on/dtparam=audio=off/' "$BOOT_CONFIG"
        echo "  $BOOT_CONFIG: dtparam=audio=on -> dtparam=audio=off"
        NEEDS_REBOOT=1
    elif ! grep -qE '^\s*dtparam=audio=off' "$BOOT_CONFIG"; then
        printf '\n# Analogue audio shares the PWM clock used by the WS2812B status LED\ndtparam=audio=off\n' >> "$BOOT_CONFIG"
        echo "  $BOOT_CONFIG: added dtparam=audio=off"
        NEEDS_REBOOT=1
    else
        echo "  Already disabled in $BOOT_CONFIG."
    fi
fi
BLACKLIST_FILE="/etc/modprobe.d/blacklist-bcm2835-audio.conf"
if [ ! -f "$BLACKLIST_FILE" ]; then
    printf 'blacklist snd_bcm2835\n' > "$BLACKLIST_FILE"
    echo "  Blacklisted snd_bcm2835 in $BLACKLIST_FILE"
    NEEDS_REBOOT=1
fi
echo ""

echo "Step 3c: Put the servo bus on the full PL011 UART"
# By default the Pi gives the PL011 (ttyAMA0: 16-byte FIFO, own clock, error
# flags) to Bluetooth and leaves the GPIO14/15 header on the mini-UART (ttyS0:
# 8-byte FIFO, clock tied to the core). At 1 Mbps the mini-UART overruns if the
# kernel is ~80 us late servicing it. miniuart-bt swaps them: /dev/serial0
# becomes ttyAMA0 and Bluetooth drops to the mini-UART (still works, at a
# lower rate). Same pins, no wiring change. Takes effect on next reboot.
if [ -f "$BOOT_CONFIG" ]; then
    if grep -qE '^\s*dtoverlay=(miniuart-bt|disable-bt)' "$BOOT_CONFIG"; then
        echo "  Already configured in $BOOT_CONFIG."
    else
        printf '\n# Servo bus on the full PL011 UART (/dev/serial0 -> ttyAMA0); Bluetooth on the mini-UART\ndtoverlay=miniuart-bt\n' >> "$BOOT_CONFIG"
        echo "  $BOOT_CONFIG: added dtoverlay=miniuart-bt"
        NEEDS_REBOOT=1
    fi
fi
if [ -L /dev/serial0 ]; then
    echo "  /dev/serial0 currently -> $(readlink /dev/serial0)$( [ "$(readlink /dev/serial0)" = "ttyAMA0" ] && echo ' (PL011, good)' || echo ' (mini-UART until reboot)')"
fi
echo ""

echo "Step 4: Install systemd service"
TEMP_SERVICE="/tmp/$SERVICE_NAME"
sed -e "s|INSTALL_DIR|$INSTALL_DIR|g" \
    -e "s|SERVICE_USER|$SERVICE_USER|g" \
    -e "s|NODE_PATH|$NODE_PATH|g" \
    -e "s|LOG_DIR|$LOG_DIR|g" \
    "$INSTALL_DIR/st3215-server.service" > "$TEMP_SERVICE"
cp "$TEMP_SERVICE" "/etc/systemd/system/$SERVICE_NAME"
rm -f "$TEMP_SERVICE"
echo "  Copied to /etc/systemd/system/$SERVICE_NAME"
echo ""

echo "Step 5: Enable and start service"
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"
echo "  Done."
echo ""

echo "=========================================="
echo "Installation complete"
echo "=========================================="
echo ""
echo "The server will:"
echo "  - Start automatically when the Pi boots"
echo "  - Restart automatically if it stops (systemd Restart=always)"
echo ""
echo "Useful commands:"
echo "  sudo systemctl status $SERVICE_NAME"
echo "  sudo systemctl restart $SERVICE_NAME"
echo "  sudo systemctl stop $SERVICE_NAME"
echo ""
echo "If restart seems stuck (old unit without TimeoutStopSec), force-stop then start:"
echo "  sudo systemctl kill -s SIGKILL $SERVICE_NAME"
echo "  sudo systemctl start $SERVICE_NAME"
echo ""
echo "Log files:"
echo "  $LOG_DIR/server-debug.log   (startup, shutdown, errors)"
echo "  $LOG_DIR/server.log         (normal console output)"
echo ""
echo "Follow logs live:"
echo "  tail -f $LOG_DIR/server-debug.log"
echo "  sudo journalctl -u $SERVICE_NAME -f"
echo ""
if [ "$NEEDS_REBOOT" = "1" ]; then
    echo "*** config.txt changed (audio off for the status LED / PL011 for the servo bus) - reboot to apply:"
    echo "***   sudo reboot"
    echo ""
fi

systemctl --no-pager status "$SERVICE_NAME" || true
